version: '3.9'
services:

  # 服务名
  tinc:
    # 模拟一个伪终端
    tty: true
    # 打开标准输入,可以接受外部输入
    stdin_open: true
    # 主机名
    hostname: tinc
    # 指定容器名称
    container_name: tinc
    # 指定为镜像名称或镜像ID
    image: danxiaonuo/tinc:latest
    # 覆盖容器启动后默认执行的命令
    # command: /sbin/init
    # 允许容器中运行一些特权命令
    privileged: true
    # 指定容器退出后的重启策略为始终重启
    restart: always
    # 指定容器的内核能力(capacity)分配
    cap_add:
     - ALL
    # 数据卷所挂载路径设置
    volumes:
      # 配置目录与文件
      - ./conf/tinc/data:/etc/tinc:rw,cached
      - ./conf/tinc/logs:/opt/tinc/logs:rw,cached
      # 同步宿主机时区与时间
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro,cached
      - /etc/localtime:/etc/localtime:ro,cached
      # 共享内核
      - /lib/modules:/lib/modules:ro,cached
      - /etc/sysctl.conf:/etc/sysctl.conf:ro,cached
    environment:
      # 选择服务端与客户端(server or client)
      - RUNMODE=server
      # 节点名称
      - NODE=server01
      # 网络接口名称
      - NETNAME=danxiaonuo
      # 网卡名称
      - INTERFACE=danxiaonuo
      # 连接服务端地址
      - PUBLIC_IP=uola.xiaonuo.live
      # 私有IPV4掩码
      - PRIVATE_IPV4_MASK=16
      # 私有IPV6掩码
      - PRIVATE_IPV6_MASK=64
      # 私有IPV4网关
      - PRIVATE_IPV4_GW=10.88.0.0
      # 私有IPV6网关
      - PRIVATE_IPV6_GW=2088::0
      # 私有IPV4地址
      - PRIVATE_IPV4=10.88.0.1
      # 私有IPV6地址
      - PRIVATE_IPV6=2088::1
      # TINC端口
      - TINC_PORT=7666
      # DEBUG等级
      - VERBOSE=4
    # 指定设备映射关系
    devices:
      - /dev/net/tun
    # 配置容器连接的网络
    network_mode: "host"
    # 指定容器的 ulimits 限制值
    ulimits:
      nproc: 65535
      nofile:
          soft: 65535
          hard: 65535
